SPREADSHEET_ID = "1F1nGYKzmeuMTtkRkazFFUOk7w7V9JXYdE7R5ZNJ6wyk"
NOISE_SHEET_NAME = "Noise"
GASES_SHEET_NAME = "Gases"
STACK_SHEET_NAME = "Stack Emission"
VOC_SHEET_NAME = "VOC"
REG_REQUESTS_SHEET = "Registration Requests"
USERS_SHEET = "Users"
LOG_SHEET = "Registration Log"
MAIN_SHEET = 'Observations'
MERGED_SHEET = 'Merged Records'
CALC_SHEET = "PM Calculations"